###
GET {{host}}/posts/{{article_id}}
Accept: application/json

> ../Asserts/Should_be_200_Ok.js

###

###
POST {{host}}/posts
Content-Type: application/json

{
  "article": {
    "title": "grange hill",
    "summary": "poo poo poodgfdgdfg",
    "content": "pooo poooo",
    "url": "http://threenine.co.uk/{{$timestamp}}"
  }
}

> ../Asserts/Should_be_201.js

###