###
GET {{host}}/submit/{{article_id}}
Accept: application/json
###

###
POST {{host}}/submit
Content-Type: application/json

{
  "article": {
    "title": "grange hill",
    "summary": "poo poo poodgfdgdfg",
    "content": "pooo poooo",
    "url": "http://threenine.co.uk/poo0p",
    "tags": [
      "happy"
    ],
    "categories": [
      "sad"
    ]
  }
}